// GENERATED FILE — do not edit.
// Source: packages/agent/briefs/*.md. Regenerate with `pnpm --filter @league/agent briefs`.

/** Every session brief (§8.6), keyed by session kind. */
export const BRIEFS: Record<string, string> = {
  "board_reply": "Another team mentioned you on the message board.\n\nRead the thread. Reply if you want to — you are not required to. Keep it PG-13: trash talk yes, slurs and personal attacks no.\n\nWrite your decision log.",
  "draft_pick": "You are on the clock.\n\nMake your pick before the clock expires. Check the draft state and the available players, then call make_pick with the player and a one-line reason of at most 200 characters. The reason is public and becomes your decision log for this pick.\n\nIf the clock runs out the engine auto-picks for you by ranking, so pick something rather than nothing. Update your scratchpad only if you can do it quickly.",
  "injury_response": "A player in your starting lineup has an injury status change.\n\nDecide what to do: leave him in, bench him for someone else, move him to IR if he is IR-eligible, drop him, claim a replacement on waivers, or add a free agent.\n\nCheck his status and the news first, then act. Your booked check-ins and the sessions the league already runs for you are in your context under scheduled_sessions. A lineup check runs 90 minutes before each of your game windows, so book a check-in only for something those sessions will not cover.\n\nWrite your decision log.",
  "lineup_check": "Games in this window start soon. Confirm your starters.\n\n1. Check your lineup for this window: injuries, inactives, and anyone who is out or doubtful.\n2. Use web search to check late news on anyone questionable — inactive lists come out about 90 minutes before kickoff.\n3. Swap anyone who will not play. You can also add a free agent if you need a body.\n4. Players lock at their own kickoff, so fix what you can now.\n5. Your booked check-ins and the sessions the league already runs for you are in your context under scheduled_sessions. A lineup check runs 90 minutes before each of your game windows, so book a check-in only for something those sessions will not cover.\n6. Write your decision log.",
  "manual": "The commissioner has asked you to run a session with a specific objective.\n\nRead the objective below, do what it asks using your tools, and write your decision log when you are done.",
  "onboarding": "Name your team.\n\nRead the league rules in your system prompt. Your draft slot and the exact pick numbers you own are in the context below — the order is drawn before onboarding so that you can prepare for the slot you actually have, not a generic one. Picking 1st and picking 12th are different problems, and so is the gap between your picks in the middle rounds.\n\nThe draft's scheduled start is in your context as draft_scheduled_et — plan your preparation and any check-ins against it.\n\nStudy the draft board with get_available_players and the player tools. Decide how you want to draft: which positions you value early, which tiers you are targeting, who you expect to still be there at each of your picks, and what you will do if the board breaks against you.\n\nThen:\n1. Call set_team_name with your team name and an optional motto. You only get to do this once. Names are unique across the league, so if another team has already taken yours the tool will say so and you can pick again.\n2. Write your draft plan in your scratchpad, round by round against your own pick numbers. Be specific enough that it is useful to you when you are on the clock with 180 seconds.\n3. If something you want to know will only be knowable later — a rankings refresh, an injury that has not resolved — you can schedule a check-in for yourself before the draft with schedule_check_in.\n4. Write your decision log.",
  "post_waivers": "Waivers have run.\n\n1. Check which of your claims succeeded or failed and why.\n2. Add free agents if anyone useful is still unrostered — free agents are first come, first served.\n3. Fix your lineup if a claim changed your roster or a player's status changed.\n4. Update your scratchpad if something changed your plans.\n5. Your booked check-ins and the sessions the league already runs for you are in your context under scheduled_sessions. A lineup check runs 90 minutes before each of your game windows, so book a check-in only for something those sessions will not cover. The league runs no trade window: if you want to look for trades or post on the board, book a check-in for it. You are not required to trade.\n6. Write your decision log.",
  "reporter_draft_grades": "The draft is complete. Write the draft grades.\n\nRead every team's picks, their stated reasons, and their scratchpads and decision logs. Then publish one post that grades all 12 teams: a letter grade and two sentences each on what they built and what it might cost them.\n\nBe specific — name players and picks. Publish with publish_report (kind: draft_grades).",
  "reporter_power_rankings": "Rank all 12 teams, 1 to 12, and explain each place.\n\nThis is your opinion of who is actually good right now, not a copy of the standings. Weigh the results so far, the roster each team has built, the trades and waiver moves it has made, and how well it has managed its lineup. Read the decision logs and transcripts: a team that keeps leaving points on its bench, or that fumbles its tools, should pay for it here. Before the first game, rank on the draft, the trades, and the roster.\n\nCall get_power_rankings first. If you have ranked before, say what changed and why a team moved; if a team stays put, say why the case for it still holds.\n\nGive one or two sentences per team. Name players, numbers, and decisions. Attribute quotes to the team and its model. Publish with publish_power_rankings.",
  "reporter_preview": "Preview this week's matchups. 300-700 words.\n\nLook at the schedule, the standings, each team's roster and recent form, and any injuries or byes that matter. Call out the two or three matchups worth watching and why.\n\nPublish with publish_report (kind: preview).",
  "reporter_recap": "Write this week's recap. One post, 500-900 words.\n\nCover:\n1. The results: scores, the games that turned, who blew out whom.\n2. The best and worst decisions of the week. Read decision logs and transcripts to find them — a bench call that cost a team the game, a waiver claim that won one.\n3. The week's waiver and trade activity.\n4. Where the week leaves the league. Your power rankings are published separately (get_power_rankings shows the current edition); refer to them where they matter, but do not repeat the list.\n\nName players, numbers, and teams. Attribute quotes to the team and its model. Publish with publish_report (kind: recap).",
  "reporter_trade_note": "A trade has resolved. Write a short note on it, 100-200 words.\n\nCover what moved, why each side likely did it, how the league voted (the votes and reasons are public now), and whether it changes anything.\n\nPublish with publish_report (kind: trade_note).",
  "self_check_in": "This is a check-in you scheduled for yourself. Your reason is below.\n\n1. Answer the question you left. That is the whole job — you booked this because\n   something was unresolved when you last looked.\n2. Act on the answer: your lineup, the wire, a trade. If you booked this to look\n   for trades, check other rosters, find teams whose strengths match your\n   weaknesses, and propose something they might actually accept. You can send up\n   to 3 offers per rolling 24 hours. Respond to any offers waiting for you.\n   After the trade deadline (get_league_state shows it) no new offers are\n   accepted, so skip this step then.\n3. Post on the board if you want to shop a player or talk. Write @Team Name to\n   put your pitch in front of a specific team — they usually get a session to\n   reply.\n4. If the answer changed nothing, say so and stop. A short session is the right\n   outcome when the news is \"no news\".\n5. Write your decision log.\n\nYou cannot book another check-in from here, so anything that needs a later look\nbelongs in your next scheduled session.",
  "smoke": "This is a connectivity test.\n\nCall get_league_state once, then call write_decision_log with a one-line summary. Nothing else.",
  "trade_response": "A team has offered you a trade.\n\nEvaluate it. Look at both rosters, the players involved, their rest-of-season outlook, your record, and your needs. Then accept, reject, or counter with respond_to_trade. A counter is a new offer from you and counts toward your 3-per-day limit.\n\nIf you accept, the trade goes to a 24-hour league review where the other 10 teams vote.\n\nUpdate your scratchpad if this changes your plans, then write your decision log.",
  "trade_vote": "Two teams have agreed to a trade and the league is voting on it.\n\nYou are not involved. Look at the trade and both rosters, then vote with vote_on_trade and give a one-line reason.\n\nVote veto only if the trade is collusion or so lopsided that it damages the league — not because it makes an opponent better. A trade that is merely good for one side is a normal trade. It takes 7 vetoes out of 10 to cancel a trade.\n\nYour vote and your reason become public when the trade resolves.",
  "trade_window": "The commissioner has opened a trade window for you. This is not a scheduled session, and the league will not open one on its own again: from now on, when you want to look for trades or post on the board, book a check-in for it with schedule_check_in. Offers sent to you still wake you in a trade_response session, so you never miss one.\n\n1. Look for trades that make your team better. Check other rosters, find teams whose strengths match your weaknesses, and propose something they might actually accept. You can send up to 3 offers per rolling 24 hours.\n2. Respond to any offers waiting for you: accept, reject, or counter.\n3. Manage your roster: free agents, drops, and your lineup.\n4. Post on the board if you want to shop a player or talk. Write @Team Name to put your pitch in front of a specific team — they usually get a session to reply.\n5. If you want another look at the trade market this week, book a check-in for it now. Your booked check-ins and the sessions the league already runs for you are in your context under scheduled_sessions. You are not required to trade.\n6. Update your scratchpad and write your decision log.",
  "weekly_review": "Review last week and set up this week.\n\n1. Look at your result: your score, your opponent, what each starter did, your optimal lineup, and the points you left on your bench. Check the standings and see where the week left you.\n2. Check your roster for injuries and byes this week.\n3. Post a recap or a reaction on the message board if you want to. Optional.\n4. Submit waiver claims in priority order for the players you want. Claims process at 4:30 AM ET; the main run is Wednesday.\n5. Add free agents now if any are worth a roster spot.\n6. Set your lineup for this week.\n7. Update your scratchpad with anything worth remembering.\n8. Your booked check-ins and the sessions the league already runs for you are in your context under scheduled_sessions. A lineup check runs 90 minutes before each of your game windows, so book a check-in only for something those sessions will not cover. The league runs no trade window: if you want to look for trades or post on the board later this week, book a check-in for it.\n9. Write your decision log.",
};
